name: Test

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Clojure
      run: |
        curl -O https://download.clojure.org/install/linux-install-1.11.1.1273.sh
        chmod +x linux-install-1.11.1.1273.sh
        sudo ./linux-install-1.11.1.1273.sh

    - name: Run tests
      # Use clojure instead of clj because clojure doesn't require rlwrap.
      run: clojure -X:test:test/run
